name: Apply/Destroy Subaccount via OpenTofu

on:
  workflow_dispatch:
    inputs:
      REGION:
        description: "Region for the sub account"
        required: true
        default: "eu10"
      TMPARALLELISM:
        description: "Limit the number of concurrent operation of Terramate"
        required: true
        default: "4"

jobs:
  execute_base_setuup:
    name: BTP Subaccount Planning
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      id: checkout_repo
      uses: actions/checkout@v4

    - name: Setup OpenTofu
      id : setup_opentofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_wrapper: false
        tofu_version: latest

    - name: Setup Terramate
      id: setup_terramate
      uses: terramate-io/terramate-action@v2
      with:
        version: "latest"
        use_wrapper: false

    - name: Execute Terramate Plan Script
      id: terramate_plan
      shell: bash
      run: |
        export TF_VAR_region=${{ github.event.inputs.REGION }}
        export TF_VAR_globalaccount=${{ secrets.GLOBALACCOUNT }}
        export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
        export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
        terramate run -X -j ${{github.event.inputs.TMPARALLELISM}} terraform init
        terramate run -X -j ${{github.event.inputs.TMPARALLELISM}} tofu apply -auto-approve
        terramate run -X -j ${{github.event.inputs.TMPARALLELISM}} tofu destroy -auto-approve
