name: Matrix via Terraform

on:
  workflow_dispatch:

jobs:
  execute_base_setup:
    strategy:
        fail-fast: false
        matrix:
          stage:
            - 'dev'
            - 'tst'
            - 'prd'
            - 'sbx'
            - 'load1'
            - 'load2'
            - 'load3'
            - 'load4'
            - 'load5'
            - 'load6'
            - 'load7'
            - 'load8'
    name: BTP Subaccount Planning
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      id: checkout_repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      id : setup_terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
        terraform_version: latest

    - name: Setup Terramate
      id: setup_terramate
      uses: terramate-io/terramate-action@v2
      with:
        version: "latest"
        use_wrapper: false

    - name: Execute Terramate Plan Script
      id: terramate_plan
      shell: bash
      run: |
        export TF_VAR_globalaccount=${{ secrets.GLOBALACCOUNT }}
        export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
        export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
        terramate script run -X --tags=${{ matrix.stage }} plan
